/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package nea.coursework.lingolink;

import javax.swing.JOptionPane;

/**
 *
 * @author nikia
 */
public class showAnswers extends javax.swing.JPanel {

    /**
     * Creates new form showAnswers
     */
    public showAnswers() {
        initComponents();
    }
    
    public void setMistake(String text) {
        mistakeLabel.setText("<html>" + text.replace("|", "<br>") + "</html>");
    }
    
    
    private void mistakeLabelMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (evt.getClickCount() == 2) { 
            String fullText = mistakeLabel.getText().replace("<html>", "").replace("</html>", "").replace("<br>", "\n");
            JOptionPane.showMessageDialog(this, 
                fullText, 
                "Mistake Details", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        mistakeLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 0));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        mistakeLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        mistakeLabel.setText("[Mistake]");
        jPanel2.add(mistakeLabel, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanel2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mistakeLabel;
    // End of variables declaration//GEN-END:variables
}
